### ISSUE TITLE
Status switch problem with register B (second half of MCP)

### ISSUE THREAD

**Issue by bigu1975** [jpcornil-git/HA-mcp23017#2]
My config:

platform: mcp23017
i2c_address: 0x20
invert_logic: true
pins:
0: MCP 8
1: MCP 7
2: MCP 6
3: MCP 5
4: MCP 4
5: MCP 3
6: MCP 2
7: MCP 1

platform: mcp23017
i2c_address: 0x20
invert_logic: true
pins:
8: MCP 15
9: MCP 14
10: MCP 13
11: MCP 12
12: MCP 11
13: MCP 10
14: MCP 9
15: MCP_NOTUSED1

platform: mcp23017
i2c_address: 0x21
invert_logic: true
pins:
0: MCP 16
1: MCP 17
2: MCP 18
3: MCP 19
4: MCP 20
5: MCP 21
6: MCP 22
7: MCP 23

platform: mcp23017
i2c_address: 0x21
invert_logic: true
pins:
8: MCP 24
9: MCP 25
10: MCP 26
11: MCP 27
12: MCP 28
13: MCP 29
14: MCP 30
15: MCP_NOTUSED2

All pins of are configured the same way.
Let's assume I power on system - initial start of HA scenario:
All switches should have the same status - On (as logic is inverted).
But only first half (pins: 0-7) of MCP switches have status On - correct. 
Second half (pins 8-15) of MCP switches have status: Off - wrong.

And my assumption is that second half of MCP report its status incorrectly (but the real pin is set correctly) as I need double action to have it synchronized again.

HA restart scenario:
After the HA restart switches keep its statuses but again only for register A (first half). Second half (register B) always shows (is changing to)  off - and again my assumption is this is fake status - and only status. Real pin is set correctly.

Many thanks in advance for the support.

Kind regards,
Bartosz

**Comment by jpcornil-git** [comment]
Hi Bartoz,

Could you change https://github.com/jpcornil-git/HA-mcp23017/blob/main/custom_components/mcp23017/__init__.py#L238



        return bool(value & (1 << bit))
with

        return bool(self._cache[register] & (1 << bit))

Cheers,
jpc

**Comment by bigu1975** [comment]
:)

Well I own you a beer. Not one :).

Thank you - of course it works now.
Highly appreciated - you save me a lot of time and solved a lot my config problems.

**Comment by jpcornil-git** [comment]
Thanks for testing/reporting as well (my tests are limited to my hardware configurations)

**Comment by bigu1975** [comment]
Hello,

 

Any time. If you would like to have tested something please let me know.
